### PR TITLE
Copy changes to homepage

### PR DESCRIPTION
**Pull request by colinswilliams**

### CODE REVIEW

**Comment by gz-c** [comment]
Build failures

Also, what changes copied to homepage?  Not clear what this PR is for

**Comment by colinswilliams** [comment]
Not sure what the build failure is about, Travis CI isn't really providing much to work off of in terms of what went wrong there. Just committed some changes to the copy and sections to more accurately align with the google doc.

The only file changes are json related, a new homepage component to support the styling of the new content, and a bit of movement of some of the content on the homepage. Which is weird, why would that cause the build to fail?

Changes requested here come from Bradford, as there will be some press coming this week, and there was a request to add more descriptive copy to the homepage. Further details about the changes are in Slack.

**Comment by colinswilliams** [comment]
Err, now travis error logs are being more specific. Weird that ESLint didn't catch these, addressing the issues now.

**Comment by colinswilliams** [comment]
Fixed linting issues

**Pull request merged**
