### PR TITLE
remove links to blog in sitemap.xml

### PR DESCRIPTION
**Pull request by chalyi-andrei**

### CODE REVIEW

**Comment by gz-c** [comment]
Why are we removing these?

**Comment by chalyi-andrei** [comment]
When there was an old sitemap.xml (without all links to /blog/...), google search result shows skycoin.net with sub links. After we added a new sitemap.xml, google search result shows skycoin.net withщге sub links. We decided to remove all external links (/blog, /explorer), and check it.

**Comment by AlexSugak** [comment]
@chalyi-andrei let's leave blog links in the sitemap and only update priority for "main" pages to see if this will help in showing sub links.

**Comment by gz-c** [comment]
Blog generates its own sitemap that we can submit to google webmaster tools, so maybe not necessary in the single sitemap either

**Pull request merged**
